#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 18 14:14:30 2019

@author: amandafoster
"""

import random

def getInput():
    return input("How many pennies?")

def getPennies():
    userinput = getInput() 
    try:
        float(userinput)
        try:
            return int(userinput)
        except ValueError as verror:
            return int(float(userinput) * 100) 
    except ValueError as verror:
        print("Invalid Input")
        return getPennies()
if __name__ == "__main__":
    print(getPennies())
    